### ISSUE TITLE
Multiple reference organisms

### ISSUE THREAD

**Issue by StevenBai97** [Jstacs/Jstacs#10]
Hello,
How to combine the predictions from multiple reference organisms by GAF ? 
My commands are "java -jar GeMoMa-1.6.4.jar CLI GAF g=species1/predicted_annotation.gff g=species2/predicted_annotation.gff g=species3/predicted_annotation.gff outdir=out" and "java -jar GeMoMa-1.6.4.jar CLI AnnotationFinalizer a=out/filtered_predictions.gff outdir=out rename=NO" Is it right?

In addition, which kind of masked genome should be used to run GeMoMa, softmask or hardmask?

**Comment by JensKeilwagen** [comment]
Hi Steven,

Your command lines look okay. To make sure that the transcriptIDs from the predictions are different, I would recommend to use a prefix for each reference species:

`java -jar GeMoMa-1.6.4.jar CLI GAF p=species1 g=species1/predicted_annotation.gff p=species2 g=species2/predicted_annotation.gff p=species3 g=species3/predicted_annotation.gff outdir=out`

Do you have any problems with these command lines?

You can use GeMoMaPipeline with runs all modules ((ERE, DenoiseIntrons), Extractor, <Search>, GeMoMa, GAF, AnnotationFinalizer) after each other and combines the results of several reference species using GAF internally.

I would use a softmasked target genome.

best regards, Jens

**Comment by StevenBai97** [comment]
> Hi Steven,
> 
> Your command lines look okay. To make sure that the transcriptIDs from the predictions are different, I would recommend to use a prefix for each reference species:
> 
> `java -jar GeMoMa-1.6.4.jar CLI GAF p=species1 g=species1/predicted_annotation.gff p=species2 g=species2/predicted_annotation.gff p=species3 g=species3/predicted_annotation.gff outdir=out`
> 
> Do you have any problems with these command lines?
> 
> You can use GeMoMaPipeline with runs all modules ((ERE, DenoiseIntrons), Extractor, , GeMoMa, GAF, AnnotationFinalizer) after each other and combines the results of several reference species using GAF internally.
> 
> I would use a softmasked target genome.
> 
> best regards, Jens

Thanks a lot for your suggestions. I'll have a try.
