### ISSUE TITLE
Update GeMoMa bioconda package

### ISSUE THREAD

**Issue by nathanweeks** [Jstacs/Jstacs#11]
The current GeMoMa bioconda package is a bit outdated (version 1.6.4). Could this be updated when convenient? Thanks!

**Comment by nathanweeks** [comment]
I went ahead and proposed an update: https://github.com/bioconda/bioconda-recipes/pull/28702

**Comment by JensKeilwagen** [comment]
Hi Nathan,

thanks a lot for your issue. You're right. The bioconda package needs to be updated. Great that you proposed an update.
