### ISSUE TITLE
GeMoMa fails if directory containing GeMoMa JAR file is not writable

### ISSUE THREAD

**Issue by nathanweeks** [Jstacs/Jstacs#12]
If the GeMoMa JAR file is located in a directory the user does not have write access to (e.g., as part of a global package installation by a sysadmin that is usable by all server/HPC cluster users; or in a Singularity Image Format (SIF) file, which contains a read-only file system providing the software environment for a Singularity container), GeMoMa will fail with an error like (e.g., in the case where the JAR is at /usr/local/bin/GeMoMa-1.6.4.jar):

> Exception in thread "main" java.io.FileNotFoundException: /usr/local/bin/GeMoMa.ini.xml (Read-only file system)

A GeMoMa.ini.xml file is apparently assumed to exist in the same directory as the GeMoMa JAR file, and if not, one is written with default values:
https://github.com/Jstacs/Jstacs/blob/c7126b12ae8ac5b711952f7f818c3b8e27ca32d0/projects/gemoma/GeMoMa.java#L321

To support these GeMoMa installation scenarios, it convenient GeMoMa defaults were silently used (instead of being written to a new file) if GeMoMa.ini.xml does not exist (or alternatively, written to the current working directory, which is likely to be writable) https://github.com/Jstacs/Jstacs/blob/c7126b12ae8ac5b711952f7f818c3b8e27ca32d0/projects/gemoma/GeMoMa.java#L319-L320

**Comment by JensKeilwagen** [comment]
Hi Nathan,

I decided to try to write the file, but use the defaults silently if it could not be written. Only a small message is written to standard error

https://github.com/Jstacs/Jstacs/blob/93c070010a48e48630f4a45379635d9d1a137daf/projects/gemoma/GeMoMa.java#L336-L340

**Comment by kullrich** [comment]
Hi, related to this issue, I do not know if I should also put it into the repo https://github.com/Gaius-Augustus/GUSHR or https://github.com/Gaius-Augustus/BRAKER
The test9 of the braker2 pipline fails, if the user has no write permissions into the GUSHR source directory.
Also, the GUSHR still has the 1.6.2 version in the python script which throws a warning to use the latest 1.7.1.
After updating the braker2 deps GUSHR directory with the latest 1.7.1 GeMoMa and having a GeMoMa.ini.xml in this directory, solved it for me.

**Comment by JensKeilwagen** [comment]
Hi Kristian,
thanks a lot for your information.
Katharina and I like to work on GUSHR. We need to update the dependencies and test the software. Unfortunately this has been delayed for a while because of various reasons.
The update for GeMoMa that I reported this morning will be included in the next version of GeMoMa.

Thanks for reporting the work-around for those who want to use it now.

**Comment by nathanweeks** [comment]
Thanks @JensKeilwagen & @kullrich !  I look forward to the updated GeMoMa (and integration in GUSHR). FWIW, I saw a java exception when I attempted to run the BRAKER example test9.sh using GeMoMa 1.7.1 (using a version of GUSHR that was lightly modified to look for GeMoMa-1.7.1.jar):
> Exception in thread "main" java.lang.NullPointerException at projects.gemoma.AnnotationFinalizer.read(AnnotationFinalizer.java:418)

**Comment by kullrich** [comment]
Hi, same for me:
```
java -jar /braker2/deps/GUSHR/GeMoMa-1.7.1.jar CLI AnnotationFinalizer 
  u=YES g=/braker2_test/example/tests/test9/genome.fa
  a=./gushr-KVDDAOVBWYJU/complete_gemoma_like.gff3
  i=./gushr-KVDDAOVBWYJU/introns.gff
  c=UNSTRANDED coverage_unstranded=./gushr-KVDDAOVBWYJU/coverage.bedgraph
  rename=NO outdir=./gushr-KVDDAOVBWYJU/

Exception in thread "main" java.lang.NullPointerException
        at projects.gemoma.AnnotationFinalizer.read(AnnotationFinalizer.java:418)
        at projects.gemoma.AnnotationFinalizer.run(AnnotationFinalizer.java:516)
        at projects.gemoma.AnnotationFinalizer.run(AnnotationFinalizer.java:468)
        at projects.gemoma.GeMoMaModule.run(GeMoMaModule.java:92)
        at de.jstacs.tools.ui.cli.CLI.run(CLI.java:426)
        at projects.gemoma.GeMoMa.main(GeMoMa.java:378)
```

**Comment by JensKeilwagen** [comment]
I think that was the reason why Katharina has not moved to the new version yet. We have changed some minor points in the output/input format and need to adjust GUSHR.

**Comment by JensKeilwagen** [comment]
Maybe it's a good idea to discuss this here: [https://github.com/Gaius-Augustus/GUSHR/issues](https://github.com/Gaius-Augustus/GUSHR/issues)

**Comment by nathanweeks** [comment]
> Maybe it's a good idea to discuss this here: https://github.com/Gaius-Augustus/GUSHR/issues

I added an issue here: https://github.com/Gaius-Augustus/GUSHR/issues/3
It's fairly minimal; any additional helpful details would be appreciated!

**Comment by jdmontenegro** [comment]
Hello everyone, I am running into the same issue as described here. However the source installation of GUSHR is writable and it ran pretty smoothly the first time around. This is only the second time I run this pipeline and it broke. Is it possible that the current braker2 pipelien runnning gusher requires there is no GeMoMa.ini.xml and if there is then it brakes the pipeline? I'll try erasing this file and run it again. Will keep you posted.

Cheers,

Juan D.
