### ISSUE TITLE
GAF with multiple species and weighting

### ISSUE THREAD

**Issue by marta-fb** [Jstacs/Jstacs#13]
Hi,

I'm trying to use multiple species annotations with GeMoMa, and now I would like to give a different weight during GAF. But I'm not sure I fully understand how to do this.

My command so far (with default w) is:
`java -jar $jar CLI GAF p=TEN g=TEN/predicted_annotation.gff p=LOX g=LOX/predicted_annotation.gff outdir=combined1`

How do I go about to make the p=LOX have a higher weight than the p=TEN annotations?
I tried this, but it looks like it's doing the opposite of what I want?
`java -jar $jar CLI GAF p=TEN g=TEN/predicted_annotation.gff p=LOX g=LOX/predicted_annotation.gff w=50 outdir=combined1`

Thanks,
Marta

**Comment by JensKeilwagen** [comment]
Hi Martha,

if you like to set the weight you can use the command line:

java -jar $jar CLI GAF p=TEN g=TEN/predicted_annotation.gff w=<weight_for_TEN> p=LOX g=LOX/predicted_annotation.gff w=<weight_for_LOX> outdir=combined1

However, you should then use `sumWeight` in (at least) one of the parameters `filter`, `sorting` or `alternative transcript filter`. The most simple way is to replace `evidence` by `sumWeight` (which will be the new default in the next version), but you can creative and use whatever you like.

Best regards, Jens
