### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by qymeng1996** [Jstacs/Jstacs#21]
Hey，
I am a new user for the GeMoMa, and I try to test the program with Athaliana data.
I use the latest version(1.8) and my code `java -jar /home/qymeng/biosoft/GeMoMa/GeMoMa-1.8.jar CLI  GeMoMaPipeline threads=10 AnnotationFinalizer.r=NO p=false o=true t=GCF_000004255.2_v.1.0_genomic.fna.gz outdir=output/ s=pre-extracted c=/home/qymeng/Gbarbadense/Annotation/Protein/Athaliana_447_Araport11.protein.fa >test.log 2>&1 &`
However, when it finished, i got a temp file `GeMoMa_temp`, which including the `filtered_predictions.gff` and `final_annotation.gff`. I have put my log file, and could you give me some suggests to solve it. 
[test.log](https://github.com/Jstacs/Jstacs/files/7417543/test.log)
Best Wishes;
Qingying

**Comment by qymeng1996** [comment]
Thanks for your quick answer and suggests, I have got the result  with no errors.
Best wishes;

**Comment by JensKeilwagen** [comment]
Great news.
Best regards, Jens
