### ISSUE TITLE
How to disable "Searching for the new GeMoMa updates ...".

### ISSUE THREAD

**Issue by xiekunwhy** [Jstacs/Jstacs#22]
Hi,

How to disable "Searching for the new GeMoMa updates ..."?

Best,
Kun

**Comment by JensKeilwagen** [comment]
Hello Kun,

thank you for your interest in GeMoMa. Currently it is not possible to disable the search for updates. We decided to always check for updates to inform the user when there is a new version. No information is sent to us. It is only checked if the latest version on the website matches the version you are using.

https://github.com/Jstacs/Jstacs/blob/0b39492684797911a5112c65710f66d409f26cde/projects/gemoma/GeMoMa.java#L263-L310

If you do not have internet access, it will indicate that you should check for updates manually, but GeMoMa can still be used.

best regards, Jens
