### ISSUE TITLE
java.lang.RuntimeException: Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by fengyanlei33** [Jstacs/Jstacs#25]
[test.log](https://github.com/Jstacs/Jstacs/files/8139485/test.log)
I used command "java -jar GeMoMa-1.7.1.jar CLI GeMoMaPipeline threads=10 t=spades.fasta s=own a=Models.gff3 g=scaffolds.fasta AnnotationFinalizer.r=NO >test.log 2>&1". Some files could run perfectly, but some failed. Below is the error, do you know how to fix it? Thank you very much! I also attached the log file.

> _Exception in thread "main" java.lang.RuntimeException: Did not finish as intended. java.util.concurrent.ExecutionException: java.lang.RuntimeException: Index 1 out of bounds for length 1
> 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
> 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
> 	at projects.gemoma.GeMoMa$TranscriptPredictor.computeTranscript(GeMoMa.java:2466)
> 	at projects.gemoma.GeMoMa$TranscriptPredictor.compute(GeMoMa.java:2266)
> 	at projects.gemoma.GeMoMa.run(GeMoMa.java:972)
> 	at projects.gemoma.GeMoMaPipeline$JGeMoMa.doJob(GeMoMaPipeline.java:1922)
> 	at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1321)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> 	at java.base/java.lang.Thread.run(Thread.java:832)_

**Comment by JensKeilwagen** [comment]
Hi fengyanlei33,

thanks a lot for your interst in GeMoMa. Unfortnately the error message does not too much. Ich check the log and there is some more information but still not enough.

Could you please test the latest GeMoMa version? If the roblem persists could you please provide a minimal example that produces the error?

Thanks a lot, Jens

**Comment by fengyanlei33** [comment]
Hi Jens,

Thank you for your reply. 
I tested with the GeMoMa v1.8, on two servers, but still got the same error. Then I checked the parameters and added "GeMoMa.e=1e-10 GeMoMa.p=1", now it's working. I guess maybe the default evalue 100 was too large for the searches. Some genes are short and the threshold were too short. 

Best, Yanlei

**Comment by JensKeilwagen** [comment]
Hello Yanlei,

thank you for testing the new version and also for varying some parameters. The parameters GeMoMa.e=100 and GeMoMa.p=10 are the default values and have been used hundreds of times without problems. A large evalue helps to find small exons. Of course, every input data is a little different and therefore the algorithm might encounter a very special case that leads to an error. 

Therefore, I would like to analyze this problem in more detail to find out the cause of the problem. Could you please provide the following 
1. the log of the broken run of version 1.8
2. the input data for a minimal example?

Many thanks in advance.

best regards, Jens

**Comment by fengyanlei33** [comment]
[contigs.zip](https://github.com/Jstacs/Jstacs/files/8151625/contigs.zip)
Hi Jens,

Thank you for the reply.
The log file was unsaved since I used screen output. 
The input data were large, here I only attached the target FASTA file. The reference genome and GFF file can be downloaded here: https://phycocosm.jgi.doe.gov/Emihu1/Emihu1.home.html (it needs login). 
Here is the command I used: java -jar GeMoMa-1.8.jar CLI GeMoMaPipeline threads=10 t='contigs.fasta' s=own a='Emihu1_FilteredModels6_2021-09-22.gff3' g='Emihu1_scaffolds.fasta' AnnotationFinalizer.r=NO

Best, Yanlei

**Comment by JensKeilwagen** [comment]
Hi Yanlei,

thanks for providing the data. I have downloaded that data and run GeMoMa v1.8.
I could reproduce the error and got some more details:
```
Problem while gene: gene_21048_
GeMoMa for species 0 split=1 throws an Exception
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Index 1 out of bounds for length 1
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at projects.gemoma.GeMoMa$TranscriptPredictor.computeTranscript(GeMoMa.java:2509)
	at projects.gemoma.GeMoMa$TranscriptPredictor.compute(GeMoMa.java:2307)
	at projects.gemoma.GeMoMa.run(GeMoMa.java:983)
	at projects.gemoma.GeMoMaPipeline$JGeMoMa.doJob(GeMoMaPipeline.java:1976)
	at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1370)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Checking the cds-parts and assignment I got:

```
$grep gene_21048_ GeMoMa_temp/GeMoMaPipeline-10608544410722265409/0/cds-parts.fasta -A1
>gene_21048_0
MSTTAGGIGHSAEKAAEKGSPLQ
>gene_21048_1
KRAAGEPGSPNRAAAEKSTFHLPAAAADAPFPEHTRQ
>gene_21048_2
LQLGAMGFMVHNIQAHERVGQRFGDQRVPPQQAAAS*

$ grep gene_21048 GeMoMa_temp/GeMoMaPipeline-10608544410722265409/0/assignment.tabular
gene_21048      mRNA_21048      0,1,1,1,2       0,0,0,0,0       scaffold_7      1       56334   56786   true    92      23      ,,,
```

Hence the gene is short, but not too short.

I'll have a look at this problem this week.

best regards, Jens

PS: BTW, I realized that most of your reference transcript were discarded (~18,500). You might like to check this.

**Comment by fengyanlei33** [comment]
Hi Jens,

Thank you for your careful checking. 
This annotation is strange. I checked its peptide sequence, which also contains three repeats of this region. I don't know. To my knowledge it's problematic. I've never seen this phenomenon in other species. I will just remove it and annotate genomes with other proteins.

Best, Yanlei

**Comment by JensKeilwagen** [comment]
Hi Yanlei,

internally, we discussed the issue you raised. Non-linear transcripts are a problem for GeMoMa. We could fix this with some additional code making things more complex. However, we believe that this is currently not necessary since non-linear transcripts haven't been reported as GeMoMa issue before. We are not sure whether the annotation is correct or might be a mistake. As we like to make reasonable predictions, we decided to extend the GeMoMa module Extractor.

Currently, the Extractor discards transcript that have some problems, e.g., missing start or stop codon, wrong phase, ... We will extend the Extractor providing the new category "not linear" of problematic transcripts. Internally, the Extractor will check all transcripts from the reference annotation and discard non-linear transcripts. As GeMoMaPipeline uses the Extractor, problematic transcripts will be discarded and the pipeline should work as intended.

This update will be available in the next release.

best regards, Jens

**Comment by JensKeilwagen** [comment]
Hi,

I've implemented the new version and tested it on your data. Interestingly, I found 355 transcripts that are not linear:
[not-linear.txt](https://github.com/Jstacs/Jstacs/files/8205316/not-linear.txt)

Please check those IDs.

best regards, Jens

**Comment by fengyanlei33** [comment]
Hi Jens, 
Thank you very much for the checking and providing the gene list. We will be careful about these annotations in the following steps. I think these annotations were wrong. There is another annotaion version of this species on NCBI, and that one doesn't have this issue. 

Best Regards,
Yanlei
