### ISSUE TITLE
GeMoMa multiple reference species

### ISSUE THREAD

**Issue by BFeldmeyer** [Jstacs/Jstacs#3]
Hello,
I try to annotate a genome using the gemoma pipeline with protein information of multiple reference species plus transcripts of my target species.

I ran the following code
java -Xmx180G -jar /cluster/software/gemoma/GeMoMa-1.6.4/GeMoMa-1.6.4.jar CLI GeMoMaPipeline \
threads=60 \
outdir=/gemoma/ \
tblastn=false \
GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO \
o=true \
t=/target_genome.fasta \
i=spec1 a=/pathtogff/spec1.gff g=/pathtogenome/spec1.fna \
i=spec2 a=/pathtogff/spec2.gff g=/pathtogenome/spec2.fna \
i=spec3 a=/pathtogff/spec3.gff g=/pathtogenome/spec3.fna \
r=MAPPED ERE.m=/target_transcriptomeReads_sort.bam

and obtain the following error message
....
Parameter a specified multiple times or not applicable for current selection(s). Could not use value(s): 
[/pathtogff/spec1.gff, /pathtogff/spec2.gff, /pathtogff/spec2.gff]

It seems that using "a" multiple times is a problem. Do I need to additionally specify s=specXY or add pre-/suffixes to "a" and "g"? Any help on how to get the pipeline running with multiple references would be appreciated.

**Comment by JensKeilwagen** [comment]
Hi Barbara,

Thanks a lot for your interest in GeMoMa.

Regarding your error, you just missed to add another parameter (s). I included it in your command line

java -Xmx180G -jar /cluster/software/gemoma/GeMoMa-1.6.4/GeMoMa-1.6.4.jar CLI GeMoMaPipeline threads=60 outdir=/gemoma/ tblastn=false
GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=/target_genome.fasta
**s=own** i=spec1 a=/pathtogff/spec1.gff g=/pathtogenome/spec1.fna
**s=own** i=spec2 a=/pathtogff/spec2.gff g=/pathtogenome/spec2.fna
**s=own** i=spec3 a=/pathtogff/spec3.gff g=/pathtogenome/spec3.fna
r=MAPPED ERE.m=/target_transcriptomeReads_sort.bam

(After a hint be another user, I included a comment in the short description some weeks ago: http://www.jstacs.de/index.php/GeMoMa#In_a_nutshell)


best regards, Jens

**Comment by Huangyizhong** [comment]
> Hello,
> I try to annotate a genome using the gemoma pipeline with protein information of multiple reference species plus transcripts of my target species.
> 
> I ran the following code
> java -Xmx180G -jar /cluster/software/gemoma/GeMoMa-1.6.4/GeMoMa-1.6.4.jar CLI GeMoMaPipeline
> threads=60
> outdir=/gemoma/
> tblastn=false
> GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO
> o=true
> t=/target_genome.fasta
> i=spec1 a=/pathtogff/spec1.gff g=/pathtogenome/spec1.fna
> i=spec2 a=/pathtogff/spec2.gff g=/pathtogenome/spec2.fna
> i=spec3 a=/pathtogff/spec3.gff g=/pathtogenome/spec3.fna
> r=MAPPED ERE.m=/target_transcriptomeReads_sort.bam
> 
> and obtain the following error message
> ....
> Parameter a specified multiple times or not applicable for current selection(s). Could not use value(s):
> [/pathtogff/spec1.gff, /pathtogff/spec2.gff, /pathtogff/spec2.gff]
> 
> It seems that using "a" multiple times is a problem. Do I need to additionally specify s=specXY or add pre-/suffixes to "a" and "g"? Any help on how to get the pipeline running with multiple references would be appreciated.

Hi,
  I have a question about the "ERE.M=/target_transcriptomeReads_sort.bam". If I have lots of tissues RNA-seq bam files  ,how can I merge them together ?
Thanks

**Comment by JensKeilwagen** [comment]
Hi Huangyizhong,
thanks for your interest in GeMoMa. Your questions should be an independent issue.

There are several ways to use multiple mapped read files (SAM or BAM).
The easiest is to use the parameter ERE.m multiple times.
(Alternatively, you can merge mapped read files, e.g.,  with samtools merge. ...)

Best regards, Jens

**Comment by Huangyizhong** [comment]
Thanks again. I have solved this problem and it works well .
Best wishes to you!
















At 2021-02-08 20:13:07, "keili" <notifications@github.com> wrote:

Hi Huangyizhong,
thanks for your interest in GeMoMa. Your questions should be an independent issue.

There are several ways to use multiple mapped read files (SAM or BAM).
The easiest is to use the parameter ERE.m multiple times.
(Alternatively, you can merge mapped read files, e.g., with samtools merge. ...)

Best regards, Jens
