### ISSUE TITLE
About the incomplete gene models predicted by GeMoMa

### ISSUE THREAD

**Issue by CrawlingSponge** [Jstacs/Jstacs#31]
Hi, Jens,
Thanks for the very useful tool. With a lot of tests of many annotated tools based on homologous annotation,  GeMoMa is the most accurate one as i known, consindering of the busco and the distributions of gene structures such as the length exon, intron, mRNA, exon number of each gene, etc. also coincide with its relatives.
here is the problem, i ve tried to predicted several mammal genomes, and most of the genes are accurate.  but still with part of gene models are incomplete. And these genes were proved as the same gene compared with the close relative sepcies, and these incomplete genes were actually annotated into several gene models by GeMoMa. So, how should i solve the problem, is there any tools to integrate these incomplete ones into one complete gene, or i just need to add some parameters before the finnal annotation from the last filter steps.

could you give me some suggestions, very appreciate !

yours, Liu

**Comment by JensKeilwagen** [comment]
Hi Liu,

Thanks a lot for your issue. Unfortunately, there is only little information about the exact problem. I would assume that you have made predictions and for some of the reference transcript you did not receive complete predictions, i.e., starting with a start codon (M) and ending with a stop codon (*). Have you checked whether the unfiltered predictions contain predictions for such reference transcripts? Is the missing start or stop codon really the problem? Did you use RNA-seq data?

Is there any characteristic of the reference transcripts with no prediction that might point to the problem? E.g. very long intron length, non-canonical splice sites, very short exons, editing, ... Based on the such hints, I might be able to make better suggestions how to handle this situation or develop an idea to further improve GeMoMa.

If the intron length is very long, you might check the parameters for maximal intron length or static intron length.

If you have non-canonical splice sites, you might use RNA-seq data.

In case of short marginal exons with a certain distance to the remaining transcript, I might refer to a new GeMoMa version. I urgently need to release a new version of GeMoMa. We already used GeMoMa version 1.9 internally. This version has several improvements including a parameter called "reduction factor". If some coding exons are not found via the search algoritm (mmseqs or tblastn), GeMoMa tries to find maringal exon of partial predictions using an internal search. The reduction factor allows to reduce the scope of the search avoiding to search for short introns too far upstream or downstream. By default the reducing factor was set to 10, which reflects the default behaviour of older GeMoMa versions. However, the user is able to decrease the reduction factor which increases the scope.

best rgeards, Jens

**Comment by CrawlingSponge** [comment]
Hi, Jens
Thanks for your kindly reply! As you mentioned the notices, I only changed the max of intron length paramater "m" by performing the survey of the reletives such as the maximum length of the intron is 1200000 within most mammals, 750000 within birds. There is no prediction problem about the start or stop codon problems. 
i ve also use the newest version to integrate the bam file after map RNA-seq to the reference genome, seems just like the pure homologous prediction.

Vertrbrate animal with extremely long gene model compared with other organisms, such as its gene strutures with the huge number number of exons, some genes even with stop codon with its inner structure like mouse, etc. So i think these special characters probably made the annotation more complex. With the predictions, the most obvious issue is that one gene model were predicted into two or more models and i ll pasta the example， as the fllowing,
+++++++++++++++++++++++++++
chro         start                end                   gene_name               gene_id
Chr1	55318566	55318874	LOC112532392	rna-XM_025150338.3_R1
Chr1	55334086	55334394	LOC112532392	rna-XM_025150338.3_R0
Chr1	65239805	65242126	LOC770705	rna-XM_040705634.2_R3
Chr1	65250823	65253144	LOC770705	rna-XM_040705634.2_R2
Chr1	79910465	79947352	LOC112992018	rna-XM_026114864.1_R0
Chr1	79952267	79997475	LOC112992018	rna-XM_026114864.1_R1
Chr1	80007332	80047099	LOC112992018	rna-XM_026114864.1_R2
+++++++++++++++++++++++++++
>rna-XM_025150338.3_R1 gene=gene_11479  gene_name=LOC112532392
ATGCCTCCACAGCCCAAAAAACGCGAAAAGGCTGACGGGAGCAGCAGCACCTATGGCAGGCGAGTTGAGC
CCATGGAGGTCGACCCGCCACGCAATGGCGAGGAGCCCATGGAGGTGGATCCACCTGCAGAGGGCGAGCC
AATGGAGGTGGACCCACCCTCTGCAGGGCTGATGGGGCACTACATCACCATGGCCGGGCTGCCTCCAGCA
CCATGGTGCCCAAAGCACTGCAAGACCGCCACGGGCTCGCAGGGACCCTCCAGGCAGCCAGCTCCCAACA
AGCGGCGCCACCCCCGTAGCCGACGCTAG
>rna-XM_025150338.3_R0 gene=gene_11480 gene_name=LOC112532392
ATGCCTCCACAGCCCAAAAAACGCGAAAAGGCTGACGGGAGCAGCAGCACCTATGGCAGGCGAGTTGAGC
CCATGGAGGTCGACCCGCCACGCAATGGCGAGGAGCCCATGGAGGTGGATCCACCTGCAGAGGGCGAGCC
AATGGAGGTGGACCCACCCTCTGCAGGGCTGATGGGGCACTACATCACCATGGCCGGGCTGCCTCCAGCA
CCATGGTGCCCAAAGCACTGCAAGACCGCCACGGGCTCGCAGGGACCCTCCAGGCAGCCAGCTCCCAACA
AGCGGCGCCACCCCCGTAGCCGACGCTAG
The genes contain complete gene struture, with ATG start, TAG stop, and they were splited into two gene models.
Actually, the gene with same gene name  were matched one gene of LOC112532392 at other species. 

So, is the any chance you could provide or pointed out some necessary parameters specially for animals, plants, fungi etc.  Cause execpt the intron length, there are also some parameters are important to predicted accurate gene models!

look forward to the new version of GeMoMa, and Congratulation for your great job, and i ll continue to follow!
Thanks very much!

yours,
Liu

**Comment by JensKeilwagen** [comment]
Hi Liu,

thanks a lot for your email. Adjustng intron length is an important step. Great that you already did it. If I understood it correctly, you also used RNA-seq data. 

However, I'm sorry I don't get your point.
I see that you have two (or more) predictions very close together. I also see that the DNA of the transcripts is identical. However, I don't see the problem. 
I also checked NCBI:
https://www.ncbi.nlm.nih.gov/gene/112532392/
rna-XM_025150338.3 seems to be a short single exon gene.

Could you please make the problem more obvious?

I could imagine that thes is a conflict between long an short predictions that overlap, but I did not see it in your example. In GAF, we cluster overlapping predictions and use these clusters to identify the final predictions. Here you can use the parameters for sorting, filter, ... to change the behaviour.

best regards, Jens

**Comment by CrawlingSponge** [comment]
Hi, Jens,
Thanks for your reply, i ve cheacked those repeat annotated genes, some gene models are actually the real gene models compared with the relatives, even the gene within relatives with only one copy gene. But still, some predicted gene models are much more copies, such as we totally identified 70 copies of TOPRS, which is only one copies in chicken. 
Annother question is that, alter filterring of the combined predictions with GAF, there are still with overlap genes. and i counted their length and  munnually filtered the shorter one. 

is there any priority of the reference sepceis, for example, if i annotate human, the priority of their relatives ( chimpanzee>monkey>dog>others) whether should be ordered and then to integrate into the final prediction by their priolrity just like the EVM weights (Transcript>>homologous>de novo). 

best regards, Liu

**Comment by CrawlingSponge** [comment]
Since without transcripts, i ve tried to use the outputs of GeMoMa as the training genes. and they integrate these predictions with EVM, and the final busco not very well.
could you give some suggestions if i use the output of GeMoMa as the de novo train.

best regards, Liu

**Comment by JensKeilwagen** [comment]
Hi Liu,

The number of predictions depend on many factors. Some are based on the input, as for instance the target genome and the reference transcripts, and some are based on GeMoMa parameters, e.g., predictions. The default value of predictions is 10. Hence, GeMoMa should at most predict 10 homologs of a single copy gene if you use a single reference. Of course, predictions for different reference do not need to overlap. Hence, if you have X_i genes of specific interest in reference i, then you can have between 0 and \sum_i X_i predictions of those genes in the target organism using multiple references.

The module GAF of GeMoMa allows to have overlapping alternative transcripts. Transcripts of different genes should not overlap in the coding region if I remember correctly. However, you can have nested genes.

If you like to increase the impact of a specific reference, you can increase the weight of its predictions in GAF. Then you should use the attribute sumWeight in the parameters sorting, filter and alternative transcript filter.

I'm no expert for de-novo gene prediction. In addition, different tools for de-novo gene prediction differ in their strengths and weaknesses. Hence, it's hard for me to give any general recommendation. You might ask Katharina Hoff for advise. She already tried to combine GeMoMa with de-novo gene prediction.

If you could provide concrete examples, I could have a closer look trying to understand if there are any algotithmic problems or bugs.

best regards, Jens

**Comment by CrawlingSponge** [comment]
Thanks very much for your kind reply!
i ve  cheacked the results carefully. since after the prediction, i also product the fuctional annotated with uniprot database and annotated the similar genes as one gene (like i mentioned the gene "TOPRS"). Then i cheacked the "filtered_predictions.gff" and  tracked back the reference gene using to perform the prediction, and i found the genes reference gene name are not always the same one, such as  TOPRS, LOC###, etc. So, i think there must be something wrong about the function annotation with uniprot database. 

again, appreciate for your kind answers，

yours,
Liu
