### ISSUE TITLE
Small gene models after GAF

### ISSUE THREAD

**Issue by CrawlingSponge** [Jstacs/Jstacs#32]
Hi, Jens,
 again, i ve got another issue confused me. Since after the prediction by GeMoMa, i ve performed the distributions of gene structures compared with the close relatives and there are some redundency small genes around 1000bp. I ve tried to filtered those genes by limited the minmum lengths of introns, cds and genes, but there are still some small gene models in redundency. Here is an example of two mammal species' gene structures, the blue one represent the close reference species annotated by NCBI, while the red one is my studied species predicted by GeMoMa. Since they are very close relatives and the gene strutures should be very conservative.  Could you give me some suggestions to make the two curves fitted together.
1. before filter  
![微信图片_20220524221455](https://user-images.githubusercontent.com/22827591/170057281-ef4b0fe8-28f2-4934-b4a1-5e9a38e3c753.png)
2. after filter the intron and small cds
![微信图片_20220524222226](https://user-images.githubusercontent.com/22827591/170058893-aeb23e4a-bd24-4e63-9a8d-101e03a85054.png)

Best regards,
Liu

**Comment by JensKeilwagen** [comment]
Hi Liu,

thanks a lot for reporting this interesting observation. I have to admit that I did not analyze this before.

Overall the plots are quite interesting. And I'm happy that they match quite well for exon and intron. However, I also see some problems, as for instance, the reference already has a spike at length of approximately 1000 for mRNA and CDS and that intron length can be very small (<30) but not small ([30,70]) in the reference. At a first look this seems not reasonable to me, but might be explained by the specific choice of the reference. Hence, I like to state that we need to be carefull not running into overfitting. 

I need to understand what you did to give a reasonable recommendation. Based on the results from GAF, you computed the length for mRNA, CDS, exon and intron. How did you do this? This is especially interesting for mRNA and CDS. If you use the results from GAF, mRNA has no UTR prediction and mRNA and CDS should have identical length. However, the plots differ. So you might use genomic coordinates to determine the length of mRNA.

The feature mRNA has the attributes aa and raa, which are the number of encoded amino acids in the predicted and the reference transcript, respectively (https://www.jstacs.de/index.php/GeMoMa#GFF_attributes). You might use this in GAF for the parameter filter, e.g., "Math.abs(raa-aa)/raa<=0.1", which states that the length difference between the prediction and the reference should be at most 10%. Of course, you could use other values ;)

In principle, I can imagine that there is a higher probablility of predicting small CDSs by chance. Hence, you might have multiple predictions for small CDS while you have a 1:1 correspondence for larger CDSs. You might use the attributes iAA or pAA or a combination of score, bestScore and maxScore (https://www.jstacs.de/index.php/GeMoMa#GFF_attributes) in the paramezter filter of the module GAF. For instance, it is possible to allow multiple predictions per reference transcript if they have similar scores, e.g., "score/Math.max(0,bestScore)>=0.8", which states that the score of the prediction must be at least 80% of the score of the best prediction for this reference transcript.  Of course, you could use other values ;)
You can also add a filter on the percentage of identical ammino acids between refernece and prediction, e.g., "iAA>=0.8".

Based on the available limited information, I would recommend the following filter:
`GAF.f="start=='M' and stop=='*' and Math.abs(raa-aa)/raa<=<X> and score/Math.max(0,bestScore)>=<Y>"`
where <X> and <Y> need to be replaced by reasonable values. 

Feel free to play around.

best regards, Jens

**Comment by JensKeilwagen** [comment]
Hi Liu,

Thanks a lot for your explanation.

There are two points that confuse me:
1) You extract the longest transcript per gene and run GeMoMa on these transcripts. Why do you do this? GeMoMa is able to handle multiple transcripts per gene in the reference.
2) You run GAF twice. Once for the predictions per reference organism and a second time after cating all these results. However, GAF allows to combine the prediction of multiple references in a single run.

BTW, if you do not specify parameters the default values will be used.

best regards, Jens

**Comment by CrawlingSponge** [comment]
Hi, Jens,
The reason I extract the longest transcript per gene is that we only used the longest transcript to perform the following analysis such as comparative genomic analysis. And I also heard that some bioinfomatic companies also deal the reference species in this way. I dont know if this would affect the predictions. 

And I will do the tests based on your suggestions  as soon as possible to see the difference.

Thanks again for your kind reply!
Best regards,
Liu
