### ISSUE TITLE
time-out warning

### ISSUE THREAD

**Issue by schraderL** [Jstacs/Jstacs#34]
Hi Jens,

I am now running `GeMoMa pipeline` with 4 reference species and RNAseq data as follows:

```
java -Xmx5G -Xms5G -Xmx70G  -jar /home/s/schradel/software/gemoma-1.8/GeMoMa-1.8.jar CLI GeMoMaPipeline threads=10 outdir=gem GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO Extractor.r=true o=true t=assembly.fasta \
$refs r=MAPPED ERE.m=s1.bam ERE.m=s2.bam
```

After a couple of hours of runtime, the process gets stuck and does not progress. Checking the output and log files, the only thing I could find was that file `GeMoMa_temp/GeMoMaPipeline-10149417817013514234/3/3/protocol_GeMoMa.txt` ends with:

```
time-out warning: rna-XM_044896866.1, rna-XM_044896869.1
```

Similarly, the protocol file for split 7 ends with 
```
time-out warning: rna-XM_044906410.1
```

This fits to the GeMoMa output for that run (see screenshot), so apparently these three RNAs are causing trouble. Can you think of anything that might explain this? 

<img width="797" alt="Bildschirmfoto 2022-07-12 um 22 21 06" src="https://user-images.githubusercontent.com/24993000/178678535-364ef611-1d7e-4aa0-85ad-efc3eb101db4.png">

Best
Lukas

**Comment by JensKeilwagen** [comment]
Hi Lukas,

time-out warnings can occur if the prediction of individual transcripts take too long. Hence, the prediction of the specific transcript is cancelled and the prediction of the next transcript is started. If a reference gene has alternative transcripts, time-out warnings can occur for several of those transcripts. 

Time-out warnings are warnings and no exceptions. Hence, the job is still running.

There is a user parameter that allows to define the time threshold when a time-out warning is thrown:
timeout http://www.jstacs.de/index.php/GeMoMa-Docs#GeneModelMapper
GeMoMa.t http://www.jstacs.de/index.php/GeMoMa-Docs#GeMoMa_pipeline

best regards, Jens
