### ISSUE TITLE
java.lang.IllegalArgumentException: At least two sequences with the same ID but different sequence:

### ISSUE THREAD

**Issue by steigeec** [Jstacs/Jstacs#39]
Hi-

Thanks for this useful annotation program!

I am running the GeMoMaPipeline using three reference species and one bam of mapped RNA-seq reads (consisting of all RNA-seq data for that species compiled with samtools merge). 
`GeMoMa GeMoMaPipeline -Xms5G -Xmx50G GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO  pc=true pgr=true t=$TARGET threads=24 outdir=/GemomaOut/ tblastn=true b=$BLAST_PATH o=true p=false r=MAPPED ERE.m=$RNA1 s=own i=species1 a=$ANN1 g=$GEN1 s=own i=species2 a=$ANN2 g=$GEN2 s=own i=species3 a=$ANN3 g=$GEN3>gemoma.out`

In phase 2 of the pipeline, the program prints multiple times, 
`Exception in thread "main"java.lang.RuntimeException: Did not finish as intended. java.lang.IllegalArgumentException: At least two sequences with the same ID but different sequence: gene-XB22166507.L`
The program ends with an exception. This message appears to be associated with the gff of one of my reference species, and each time the message is printed that same gene name is specified. However, if I search the 9th column of that gff file (ID=...), that ID only occurs once. Just in case, I checked the other two gff files, and neither include this same ID. 

Do you know what might be causing this exception?

Thank you!

**Comment by JensKeilwagen** [comment]
Hi,

thanks a lot for your interest in GeMoMa. Please excuse my late reply. I was on vacation.

At a first look, I did not see a reason for the problem. But I would be happy to solve the problem. Could you please provide additional information:
1) if possible the reference gene annotation files
2) more information form the protocol
to narrow down the error?

best regards, Jens

**Comment by steigeec** [comment]
Hi, Jens-

Happy New Year! I have now been working on running outside of the pipeline, so that I could have a better idea of what was throwing the exception. The annotation file is the [genomic gff here](https://www.ncbi.nlm.nih.gov/assembly/GCF_017654675.1/). What I have run with this file is

```
GeMoMa Extractor c=true genomic=true p=false a=$ANN g=$GENOME

tblastn -outfmt "6 std sallseqid score nident positive gaps ppos qframe sframe qseq sseq qlen slen salltitles" -query cds-parts.fasta -html -num_threads 25 -db $DB -word_size 3 
```

Thank you for your help!

**Comment by JensKeilwagen** [comment]
Hi,

I just had a quick view into the annotation and found the following line:

for the gene:
`NC_054371.1	Gnomon	gene	10317494	10332849	.	-	.	ID=gene-XB22166507.L [provisonal];Dbxref=GeneID:108697441,Xenbase:XB-GENE-22166509;Name=XB22166507.L [provisonal];gbkey=Gene;gene=XB22166507.L [provisonal];gene_biotype=protein_coding`

for an mRNA:
`NC_054371.1	Gnomon	mRNA	10317494	10332849	.	-	.	ID=rna-XM_041586806.1;Parent=gene-XB22166507.L [provisonal];Dbxref=GeneID:108697441,Genbank:XM_041586806.1,Xenbase:XB-GENE-22166509;Name=XM_041586806.1;gbkey=mRNA;gene=XB22166507.L [provisonal];model_evidence=Supporting evidence includes similarity to: 3 ESTs%2C and 100%25 coverage of the annotated genomic feature by RNAseq alignments%2C including 9 samples with support for all annotated introns;product=uncharacterized protein containing Ig superfamily v domain L homeolog%2C transcript variant X2;transcript_id=XM_041586806.1`

What caught my eye was the gene ID, which contains a space (`gene-XB22166507.L [provisonal]`). I've never seen this before. Checking this annotation file, only 3 genes (`gene-XB22166507.L [provisonal]`, `gene-XFG 5-1`, `gene-prss8l.5.S loc108703873`) and 9 mRNAs had such and ID or Parent-ID, respectively.

Currently, the Extractor uses the gene ID as it is and adds a suffix for the cds parts fasta file. However, in the fasta file a space is typically used as delimiter for the ID. Hence, if the gene contains several coding exons, the CDS parts fasta file will contain multiple lines like:

```
>gene id with space _0
MXXXXX
>gene id with space _1
XXXXX
```

The search algorithm will cut such sequence identifiers at the first whitespace (`gene`) and ignore everything after the whitespace (="additional information").
Hence, the error message makes sense:

```Exception in thread "main"
java.lang.RuntimeException: Did not finish as intended. java.lang.IllegalArgumentException: At least two sequences with the same ID but different sequence: gene-XB22166507.L
``` 

The current GeMoMa version does not have a solution. However, you could easily modify the annotation file by hand solving those issues. (Alternatively, you could modify the cds parts fasta file and the assignment file.) Please let me know if this works.

For the furture, we will discuss internally how to handle with such cases and will provide a solution for the next GeMoMa version. I'll keep you updated.

best regards, Jens

**Comment by JensKeilwagen** [comment]
We discuss internally and decided to implement two things:

1. an optional parameter **replace** that allows to replace whitespace characters in gene IDs
2. a check of duplicated geneIDs in the Extractor.

I already implemented both and commited it  into the repository. It will be available with the next GeMoMa release. 

best regards, Jens

**Comment by steigeec** [comment]
Thanks so much, Jens! -

I should have noticed the space and realized it might cause and issue... very understandable. These features sound great. 

My best, 
Emma
