### ISSUE TITLE
GeMoMaPipeline including lots of RNA-seq bam files

### ISSUE THREAD

**Issue by Huangyizhong** [Jstacs/Jstacs#4]
Hello,
 The GeMoMa is a proper software for me to do the prediction of genes in mammalian. I have downloaded the GeMoMa-1.7.1.jar to do it . When I combine the RNA-seq bam files to predicted the genes , I do not known how to merge all the bam files together (about 38 tissues).  I have revised the codes " java -cp GeMoMa-<version>.jar projects.gemoma.CombineIntronFiles <output name> <input0> <input1> " ,but it does not work.  
Need help!
Thanks!

**Comment by JensKeilwagen** [comment]
Hi Huangyizhong,
please take my appologies for the delay in getting back to you.
If you have multiple RNA-seq bams there are multilple ways to use them in GeMoMa:
0) You can merge the bam files using external programs like samtools.
1) You can run ERE independently on each of the bam files. You will then receive multiple intron gffs (in your case 38), which can be combined with CombineIntronFiles and then be used in GeMoMa(Pipeline).
2) You can directly use the bam files as input for the GeMoMaPipeline using the parameter ERE.m multiple times. 

Does this help?

Best regards, Jens
