### ISSUE TITLE
Using RNA-seq from closely-related organism

### ISSUE THREAD

**Issue by steigeec** [Jstacs/Jstacs#40]
Hi! -

Thanks again for the useful program!

I would like to make use of RNA-seq data for the closest-related organisms for which data is available, at least to see how it might help annotations. I have data for many tissue types, and initially mapped them to my reference genome, merged bams, indexed, then used in ERE. Although with bamstats this mapping seems to have gone well (711 million reads are mapped), using `GeMoMa ERE m=$RNA s=FR_FIRST_STRAND`, where $RNA is my merged/indexed bam,  I get an empty .gff file. I used FR_FIRST_STRAND because I believe my RNA-seq data is TruSeq ([e.g.](https://www.ncbi.nlm.nih.gov/sra/SRR11583963)), though I have experimentally tried other s options. Do you know what might be happening?

```
file statistics:
0	false	TranscriptResources/rnaseq.bam

overall statistics:
#files:	1
#corrupt files:	0
#reads:	1002408184
#split reads:	0
#questionable split reads:	0
#removed very short intron:	0
#introns:	0
#intron length:	2147483647 .. -2147483648

mapping qualities:
0-39	~300million reads	0 used reads	0 split reads               <-until here are discarded due to minimum map qual of 40
40	28932312 reads	28932312 used reads	0 split reads
41	2663338 reads	2663338 used reads	0 split reads
42	4329883 reads	4329883 used reads	0 split reads
43	3082543 reads	3082543 used reads	0 split reads
44	3444935 reads	3444935 used reads	0 split reads
45	5047684 reads	5047684 used reads	0 split reads
46	9114847 reads	9114847 used reads	0 split reads
47	3903113 reads	3903113 used reads	0 split reads
48	4122858 reads	4122858 used reads	0 split reads
49	4259958 reads	4259958 used reads	0 split reads
50	3526281 reads	3526281 used reads	0 split reads
51	3577584 reads	3577584 used reads	0 split reads
52	7327936 reads	7327936 used reads	0 split reads
53	3361437 reads	3361437 used reads	0 split reads
54	7514747 reads	7514747 used reads	0 split reads
55	3999037 reads	3999037 used reads	0 split reads
56	4756347 reads	4756347 used reads	0 split reads
57	4648650 reads	4648650 used reads	0 split reads
58	5814773 reads	5814773 used reads	0 split reads
59	5990352 reads	5990352 used reads	0 split reads
60	481850384 reads	481850384 used reads	0 split reads

```

Thank you!

**Comment by JensKeilwagen** [comment]
Hi,

The BAM file seems to be valid (cf. `#corrupt files:	0`) and ERE also found reads (cf. `#reads:	1002408184`). However, no split read was found (cf. `#split reads:	0`), which seems to be unrealistic for RNA-seq data.

Read mapper that do not allow split reads (like bwa mem), could produce such a BAM file without split reads leading to such a result. You need to use a read mapper that allows split reads, e.g. bowtie. 

Does this help?

BTW, you do not need to merge the individual BAM files. You can run ERE with multiple bam files. 

best regards, Jens
