### ISSUE TITLE
How does GeMoMa treat masked nucleotides? 

### ISSUE THREAD

**Issue by ZexuanZhao** [Jstacs/Jstacs#42]
Hi GeMoMa team,

Thank you for developing GeMoMa. I tested GeMoMa on one of my reference genomes using 10 other reference species's annotation without RNA seq data. It predicts 19000 genes while the original annotation (based on RNA seq) has about 12000 genes. Besides the problem with increasing number of genes predicted as increasing number of references provided, I also wonder if transposable elements could cause the problem so I want to test running GeMoMa on masked genome. 

Before I run, I want to confirm if GeMoMa ignore/down-weigh soft masked genome (changing from upper case to lower case) or should I hard-mask the genome?

Thanks,
Zexuan

**Comment by JensKeilwagen** [comment]
Hi Zexuan,

thanks a lot for your interest in GeMoMa.

The number of predicted genes depends on many factors. Especially it depends on the parameters of GAF which allows to filter and discard predictions based on user-specific criteria. You can make these criteria more conservative. However, it is easier to judge predictions if you have experimental evidence from RNA-seq or Iso-seq. (Furthermorre, I have to ask how confident you are that the original annotation is complete?)

Regarding masked genomes, GeMoMa ignores the case of the letters. Hence, the predictions of a soft-masked genome should be the same as for an unmasked genome.

best regards, Jens
