### ISSUE TITLE
Why does GeMoma annotationfianlizer remove the exon features ?

### ISSUE THREAD

**Issue by joleneyue** [Jstacs/Jstacs#47]
Dear Jens,

i have another question to ask you.

i used TEBRA to combine braker 1 and braker2 annotation and then used the GeMoma annotationfinalizer to add UTRs.

This is my original gff file : 

HiC_scaffold_1  AUGUSTUS        gene    3484    5786    .       -       .       ID=Bpus_H_g1
HiC_scaffold_1  AUGUSTUS        mRNA     3484    5786    .       -       .       ID=Bpus_H_g1.t1;Parent=Bpus_H_g1
HiC_scaffold_1  AUGUSTUS        exon    3484    3726    .       -       .       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        exon    4045    4137    .       -       .       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        exon    4373    4502    .       -       .       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        exon    4875    4934    .       -       .       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        exon    5175    5400    .       -       .       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        exon    5582    5786    .       -       .       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        CDS     3484    3726    .       -       0       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        CDS     4045    4137    .       -       0       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        CDS     4373    4502    .       -       1       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        CDS     4875    4934    .       -       1       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        CDS     5175    5400    .       -       2       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        CDS     5582    5786    .       -       0       Parent=Bpus_H_g1.t1

This is the gff after the genome annotationfinalizer running: 

HiC_scaffold_1  AUGUSTUS        gene    2124    10618   .       -       .       ID=Bpus_H_g1
HiC_scaffold_1  AUGUSTUS        mRNA    2124    10618   .       -       .       ID=Bpus_H_g1.t1;Parent=Bpus_H_g1
HiC_scaffold_1  AnnotationFinalizer_    five_prime_UTR  9293    10618   .       -       .       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AnnotationFinalizer_    five_prime_UTR  5787    8846    .       -       .       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        CDS     5582    5786    .       -       0       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        CDS     5175    5400    .       -       2       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        CDS     4875    4934    .       -       1       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        CDS     4373    4502    .       -       1       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        CDS     4045    4137    .       -       0       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AUGUSTUS        CDS     3484    3726    .       -       0       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AnnotationFinalizer_    three_prime_UTR 3471    3483    .       -       .       Parent=Bpus_H_g1.t1
HiC_scaffold_1  AnnotationFinalizer_    three_prime_UTR 2124    3139    .       -       .       Parent=Bpus_H_g1.t1

i noticed after running the annotationfinalizer, my gff file lost the exons features, which leads to the gffread unable to extract the UTR features for the transcripts.fa. 

Do you know why the exons features are lost? 

Thanks a lot!

Cheers,
Yuling

**Comment by JensKeilwagen** [comment]
Hi Yuling,

GAF was initially developed for GeMoMa. GeMoMa mainly focusses on CDS features. Hence, exon features were (mainly) redundant increasing the size of the annotation file. Typically features like UTRs or CDS directly use a mRNA-feature as parent as shown here:
https://www.ncbi.nlm.nih.gov/genbank/genomes_gff/

Hence, we did not see any reason to include exon features into our annotation. 

Reading ggfread, I cannot state what's the problem. YOu might check their documentation or get in touch with the developers.

best regards, Jens

**Comment by colindaven** [comment]
Can you please put exon features back into the annotation ? They are needed for many tools, such as using RNA-seq quantification (at least in our pipeline) getting exon statistics with gt stats etc.

Using exons is a standard part of gff3 to my knowledge. Here's an example from Ensembl plants, and well at least one specs page: https://www.ensembl.org/info/website/upload/gff3.html.

```
###
1	araport11	gene	3631	5899	.	+	.	ID=gene:AT1G01010;Name=NAC001;biotype=protein_coding;description=NAC domain containing protein 1 [Source:NCBI gene (formerly Entrezgene)%3BAcc:839580];gene_id=AT1G01010;logic_name=araport11
1	araport11	mRNA	3631	5899	.	+	.	ID=transcript:AT1G01010.1;Parent=gene:AT1G01010;Name=NAC001-201;biotype=protein_coding;tag=Ensembl_canonical;transcript_id=AT1G01010.1
1	araport11	five_prime_UTR	3631	3759	.	+	.	Parent=transcript:AT1G01010.1
1	araport11	exon	3631	3913	.	+	.	Parent=transcript:AT1G01010.1;Name=AT1G01010.1.exon1;constitutive=1;ensembl_end_phase=1;ensembl_phase=-1;exon_id=AT1G01010.1.exon1;rank=1
1	araport11	CDS	3760	3913	.	+	0	ID=CDS:AT1G01010.1;Parent=transcript:AT1G01010.1;protein_id=AT1G01010.1
```

**Comment by jgraux** [comment]
Did you try to use the "tf" (transfer features) parameter of AnnotationFinalizer and/or GAF. If set to true, this should transfer all previously features like UTRs and exons into the final annotation.

**Comment by colindaven** [comment]
Thanks for the hint. Can I run that feature like this:

`java -Xmx80g -jar /opt/micromamba/share/gemoma-1.9-0/GeMoMa-1.9.jar CLI GeMoMaPipeline threads=16 outdir=$prefix2 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO AnnotationFinalizer.tf=true o=true t=$fasta $gemoma_inputs`

**Comment by colindaven** [comment]
It seems the correct usage is `AnnotationFinalizer.t=true`

`java -Xmx80g -jar /opt/micromamba/share/gemoma-1.9-0/GeMoMa-1.9.jar CLI GeMoMaPipeline threads=16 outdir=$prefix2 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO AnnotationFinalizer.t=true o=true t=$fasta $gemoma_inputs`

with .tf as above I got this error:

`  Unknown parameters: {AnnotationFinalizer.tf=[true]}`

**Comment by jgraux** [comment]
Yes, AnnotationFinalizer.t=true should be correct for GeMoMaPipeline.

I was not aware that you are not using AnnotationFinalizer as a standalone tool but within GeMoMaPipeline. Some parameter names change in that case, since we avoid collisions but at the same time try to keep parameter names short.

**Comment by colindaven** [comment]
OK - sorry that wasn't clear, I'm not too well versed on Gemoma modes.

Unfortunately I'm now getting core dumps from mmseqs with the new command suggested on the same datasets which run though fine without the `AnnotationFinalizer.t=true` parameter. Will try to set cores to 1 and retry.

```

# worked fine
java -Xmx80g -jar /opt/micromamba/share/gemoma-1.9-0/GeMoMa-1.9.jar CLI GeMoMaPipeline threads=16 outdir=$prefix2 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=$fasta $gemoma_inputs


# core dump mmseqs
java -Xmx80g -jar /opt/micromamba/share/gemoma-1.9-0/GeMoMa-1.9.jar CLI GeMoMaPipeline threads=16 outdir=$prefix2 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO AnnotationFinalizer.t=true o=true t=$fasta $gemoma_inputs
```

```
threads - The number of threads used for the tool, defaults to 1        = 16
[mmseqs]: 16.747c6
[mmseqs]: Segmentation fault (core dumped)
[mmseqs]: Error: Prefilter died
[mmseqs]: Error: Search step died
18 jobs did not finish as expected. Please check the output carefully.
Did not delete temporary files allowing to debug.

java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
        at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)
        at projects.gemoma.GeMoMaPipeline$1.run(GeMoMaPipeline.java:609)
        at projects.gemoma.GeMoMaPipeline$FlaggedRunnable.run(GeMoMaPipeline.java:1409)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by colindaven** [comment]
Thanks for considering this. I will open another issue if I have more problems with core dumping.
