### ISSUE TITLE
Issues with CLI Analzyer

### ISSUE THREAD

**Issue by beantkapoor786** [Jstacs/Jstacs#56]
Hello, thank you for this amazing tool. I have predicted annotations using GeMoMa v1.9 in red oak genome using the reference genome annotation and wanted to compare both the annotation. For that purpose, I used the `Analyzer` command -

```bash
java -jar /pickett_flora/software/GeMoMa-1.9/GeMoMa-1.9.jar CLI Analyzer \
         t=../Qrubra_687_v2.1.gene.gff3 \
         n="test" \
         p=final_annotation.gff \
         w=YES \
         outdir=output/
```

It gives the following output -

```
number of true CDSs     41,587
number of true genes    33,333
number of true CDSs per true gene       1.25


category        test

number of predicted CDSs        40,821
number of predicted genes       34,159
number of predicted CDSs per predicted gene     1.20

number of perfectly predicted CDSs      0

number of true genes with at least one perfectly predicted CDS  0
number of predicted genes with at least one perfectly predicted CDS     0

CDS sensitivity 0.00
CDS precision   0.00
CDS F1  NaN

gene sensitivity        0.00
gene precision  0.00

```

I am wondering why all the annotation performance metrics are `0.00`.  I have attached both the gff files here. Please let me know your thoughts. Thank you.

[final_annotation.gff.gz](https://github.com/Jstacs/Jstacs/files/14498262/final_annotation.gff.gz)
[Qrubra_687_v2.1.gene.gff3.gz](https://github.com/Jstacs/Jstacs/files/14498263/Qrubra_687_v2.1.gene.gff3.gz)

**Comment by JensKeilwagen** [comment]
Hi beantkapoor786,

thanks a lot for your interest in GeMoMa.

I had a quick look into your files and it seems that both annotations refer to different genomes. (The chromosome identifiers look different.) Analyzer is not intended to compare annotations from different genomes. It is itended to measure the performance in cases where the truth is known. E.g. you have a given annotation for your species an compare it with the annotation produced by GeMoMa for the same species.

Does this help?

Best regards, Jens

**Comment by beantkapoor786** [comment]
Hi JensKeilwagen, thank you for your super quick reply. I see the problem here. They are indeed two different genomes however they are the same species (_Quercus rubra_). Chromosome names and unplaced scaffolds names are not identical between genome files. I am guessing I would have to find a different tool to compare these annotations. Please let me know if that's the case. Thank you.

**Comment by JensKeilwagen** [comment]
Yes, Analyzer is not able to compare the annotations from different genomes.
The question is how do you like to compare the annotations? Synteny? ...

**Comment by JensKeilwagen** [comment]
Hi beantkapoor786,
Any news from your side? Could I close the issue?
best regards, Jens

**Comment by beantkapoor786** [comment]
Hello,

Yes, I was interested in comparing the annotation between the two genome files and was able to do that. Thank you for your assistance, this issue can be resolved.

Again, thanks!
Beant
