### ISSUE TITLE
Memory error despite plenty of available memory

### ISSUE THREAD

**Issue by Sven-Winter** [Jstacs/Jstacs#59]
Hi, 
I am running GeMoMa on a HPC Cluster  and despite allowing for 1.4 TB memory I receive the following error near the end (after phase 6) of the pipeline: 

starting phase 6 (5909.686s)
============================
Starting: SyntenyChecker (5909.686s)
Starting: Extractor for final prediction (5910.208s)
Finished: SyntenyChecker (5911.844s)
Finished: Extractor for final prediction (5941.699s)
Statistics:
Job     WAITING RUNNING INTERRUPTED     FAILED  SUCCEEDED
---------------------------------------------------------
MmseqsCreateDB  0       0       0       0       1
EREAndFill      0       0       0       0       1
ExtractorAndSplit       0       0       0       0       6
Mmseqs  0       0       0       0       6
GeMoMa  0       0       0       0       240
Cat     0       0       0       0       6
GAF     0       0       0       0       1
AnnotationFinalizer     0       0       0       0       1
Extractor       0       0       0       0       1
SyntenyChecker  0       0       0       0       1
No errors detected.
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
        at java.lang.StringCoding.encode(StringCoding.java:344)
        at java.lang.String.getBytes(String.java:918)
        at de.jstacs.utils.Compression.zip(Compression.java:71)
        at de.jstacs.parameters.FileParameter$FileRepresentation.getContent(FileParameter.java:632)
        at projects.gemoma.GeMoMaPipeline.run(GeMoMaPipeline.java:1167)
        at projects.gemoma.GeMoMaModule.run(GeMoMaModule.java:94)
        at de.jstacs.tools.ui.cli.CLI.run(CLI.java:426)
        at projects.gemoma.GeMoMa.main(GeMoMa.java:399)

Any idea what could cause this? I have tried to reduce the references from 8 to 6 but received the same error. However, it previously worked with 2 references. 

Thanks in advance!
Sven

**Comment by JensKeilwagen** [comment]
Hi Sven,

Thanks a lot for your interest in GeMoMa.
I've not seen this error before. It seems that the run with 6 reference was successfull and "No error detected".
However, while preparing the results for the final output you receive an out of memory exception.
https://github.com/Jstacs/Jstacs/blob/0429b953a5dfb236d5a4e83e677e748b8514c672/projects/gemoma/GeMoMaPipeline.java#L1162C3-L1170C4

It would be great if you can provide more information to analyze this problem.
Hence, could you please provide the complete command line and the complete log? How big are your input files?

best regards, Jens

**Comment by Sven-Winter** [comment]
Hi Jens, 

Thank you for your quick reply. 

I used the following command (line breaks look weird but in my command, each reference is in one line):
java -Xmx1300g -jar /projappl/project_2006770/software/GeMoMa-1.9.jar CLI GeMoMaPipeline threads=40 outdir=. GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true pc=true pgr=true r=MAPPED ERE.s=FR_UNSTRANDED ERE.m=/scratch/project_2007386/uralowl/annotation/S3B_rna_mapped_sortedAligned.sortedByCoord.out.bam \
  t=/scratch/project_2007386/uralowl/annotation/S3B_Suralensis_v1.0.fasta.masked.masked.fasta \
  s=own i=Gagal a=/scratch/project_2007386/uralowl/annotation/references/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.gff g=/scratch/project_2007386/uralowl/annotation/references/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.fna \
  s=own i=AthCun a=/scratch/project_2007386/uralowl/annotation/references/GCF_003259725.1_athCun1_genomic.gff g=/scratch/project_2007386/uralowl/annotation/references/GCF_003259725.1_athCun1_genomic.fna \
  s=own i=TyAl a=/scratch/project_2007386/uralowl/annotation/references/GCF_018691265.1_T.alba_DEE_v4.0_genomic.gff g=/scratch/project_2007386/uralowl/annotation/references/GCF_018691265.1_T.alba_DEE_v4.0_genomic.fna \
  s=own i=CotJap a=/scratch/project_2007386/uralowl/annotation/references/GCF_001577835.2_Coturnix_japonica_2.1_genomic.gff g=/scratch/project_2007386/uralowl/annotation/references/GCF_001577835.2_Coturnix_japonica_2.1_genomic.fna \
  s=own i=GymCal a=/scratch/project_2007386/uralowl/annotation/references/GCF_018139145.2_ASM1813914v2_genomic.gff g=/scratch/project_2007386/uralowl/annotation/references/GCF_018139145.2_ASM1813914v2_genomic.fna \
  s=own i=ColStr a=/scratch/project_2007386/uralowl/annotation/references/GCF_028858725.1_bColStr4.1.hap1_genomic.gff g=/scratch/project_2007386/uralowl/annotation/references/GCF_028858725.1_bColStr4.1.hap1_genomic.fna \
#  s=own i=DryPub a=/scratch/project_2007386/uralowl/annotation/references/GCF_014839835.1_bDryPub1.pri_genomic.gff g=/scratch/project_2007386/uralowl/annotation/references/GCF_014839835.1_bDryPub1.pri_genomic.fna \
#  s=own i=PogPus a=/scratch/project_2007386/uralowl/annotation/references/GCF_015220805.1_bPogPus1.pri_genomic.gff g=/scratch/project_2007386/uralowl/annotation/references/GCF_015220805.1_bPogPus1.pri_genomic.fna


The references are all from GenBank. The genomes are between 890M and 1.2 Gb and the annotation files are between 187M and 660M I had to remove one eagle genome (GCF_900496995.4)
1.1G Jun 24  2019 GCF_003259725.1_athCun1_genomic.fna
216M Jun 24  2019 GCF_003259725.1_athCun1_genomic.gff
897M Feb 19  2020 GCF_001577835.2_Coturnix_japonica_2.1_genomic.fna
1.2G Aug 10  2021 GCF_018691265.1_T.alba_DEE_v4.0_genomic.fna
360M Aug 10  2021 GCF_018691265.1_T.alba_DEE_v4.0_genomic.gff
1018M Mar  4  2022 GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.fna
660M Mar  4  2022 GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.gff
336M Sep 29  2022 GCF_001577835.2_Coturnix_japonica_2.1_genomic.gff
1.2G Feb 27  2023 GCF_018139145.2_ASM1813914v2_genomic.fna
187M Feb 27  2023 GCF_018139145.2_ASM1813914v2_genomic.gff
1.2G Mar 14  2023 GCF_014839835.1_bDryPub1.pri_genomic.fna
168M Mar 14  2023 GCF_014839835.1_bDryPub1.pri_genomic.gff
1.2G Jan  3  2024 GCF_028858725.1_bColStr4.1.hap1_genomic.fna
263M Jan  3  2024 GCF_028858725.1_bColStr4.1.hap1_genomic.gff
1.2G Apr  1 17:50 GCF_015220805.1_bPogPus1.pri_genomic.fna
307M Apr  1 17:50 GCF_015220805.1_bPogPus1.pri_genomic.gff
[slurm-23203786.txt](https://github.com/user-attachments/files/17012326/slurm-23203786.txt)

**Comment by JensKeilwagen** [comment]
Hi Sven,

I just talked to Jan. We have never seen a problem like this before. We assume that it is not really a "out of memory" issue as the error message states "Requested array size exceeds VM limit". Hence, we assume some result file might be larger than 2 GB, which could potentially lead to such an error. 

For the future, we were talking about a different way to handle result files, but for the moment we would like to ask you whether you could check the GeMoMa_temp directory. There should be a subdirectory for the job that crashed. All the results and some other stuff should be in there. It would be great, if you could provide more information about this directory. Maybe you could do a "ls -lR".

We would then be able to see which file may cause the problem.

best regards, Jens

**Comment by Sven-Winter** [comment]
Hi, 
yes sure please find attached the ls -IR of the directory

Best, 
Sven 
[tmp_dir_files.txt](https://github.com/user-attachments/files/17014236/tmp_dir_files.txt)

**Comment by JensKeilwagen** [comment]
Hi Sven, 

thanks a lot. I had a look into the list of files. It seems that from results the genomic.fasta is the largest with about 1GB:
-rw-rw----  1 svwinter project_2007386   78119562 Sep 13 00:12 final_annotation.gff
-rw-rw----  1 svwinter project_2007386   96901942 Sep 13 00:12 cds.fasta
-rw-rw----  1 svwinter project_2007386 1001772989 Sep 13 00:12 genomic.fasta
-rw-rw----  1 svwinter project_2007386   43823052 Sep 13 00:12 proteins.fasta
The other files are quite small and should not be the problem.
You can restart the pipeline and set pgr=false (which is the default).
If the job ends without error, we definitely know that this file leads to the exception.

best regards, Jens

**Comment by Sven-Winter** [comment]
Hi Jens, 
this now works perfectly fine even on the smaller node with only 360G memory and all 8 references. Thank you very much!

**Comment by JensKeilwagen** [comment]
Great
