### ISSUE TITLE
Catchitt tutorial:  "ERROR  BBFile header is unrecognized type, header magic = -498368882"

### ISSUE THREAD

**Issue by jcness216** [Jstacs/Jstacs#6]
Has anyone gotten this error when doing the tutorial and running the DNase-seq access tool?

This is my input (on mac, installed Catchitt Java file ):
java -Xmx512m -jar Catchitt-0.1.3.jar access d="Bigwig" i=ENCFF901UBX.bigWig f=GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.fai b=50 outdir=.

**Comment by jgraux** [comment]
Using exactly the command line you specified (including the -Xmx512m VM argument), I get a java.lang.OutOfMemoryError (using OpenJDK build 11.0.1+13-LTS).

If I remove the memory limit, I do not get any errors and the expected output file.

So I would assume that either the memory limit has some side effect on your system (OS, Java version), or the file download of the Bigwig file has been corrupted. For the latter, you could check the MD5sum of your local file. According to ENCODE, this should be 2d4042c08a88bc6bb72e9a73fa7d30ea, and I got the same for my local file.

The error message you reported is from the IGV BBFileReader (see https://github.com/lindenb/bigwig/blob/master/src/org/broad/igv/bbfile/BBFileReader.java), which we use internally for reading Bigwig files, and should indicate a corrupted header of the Bigwig file.
